services:
  - type: web
    name: whack-an-error
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whack-an-error-db
          property: connectionString

databases:
  - name: whack-an-error-db
    databaseName: whack_error_db
    user: whack_user
    plan: free
